module.exports={
    devServer:{
        proxy:{
            '/api':{
                target:"http://169.254.51.20:3000",
                changeOrigin:true,
                pathRewrite:{
                    '/api':''
                }
            }
        }
    }
}